In [2]:
import numpy as np
a = np.arange(10)
print(a)
print(np.eye(3))

[0 1 2 3 4 5 6 7 8 9]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
a = np.arange(4)
a = np.random.random_sample(4)
a1 = np.array([1,2,3,5,6,8])
a2 = np.array([1,2,4,5,3,4])
c = np.dot(a1,a2)
c


X = np.array([[1],[3],[3],[4]])
w = np.array([2]) 
c1 = np.dot(X[1],w)
c1

6